# DEV ENVIRONMENT COMPOSE FILE
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/logs/nginx:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:81 # API
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    image: php-fpm-mysql
    volumes:
      - ./api:/var/www/api
    depends_on:
      - mysql
      - redis

  supervisor:
    image: php-fpm-mysql
    volumes:
      - ./api:/var/www/api
      - ./docker/logs/supervisor:/var/log
    depends_on:
      - mysql
      - redis
      - php
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

  redis:
    image: redis:8.0
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis:/data
    ports:
      - 6001:6379

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/dumps/:/tmp
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql-data:
    driver: local
  redis:
    driver: local
